import { LangCode } from './i18n';

export interface DailyTask {
  id: string;
  hour: number; // hour-of-day trigger
  amountMl: number;
  label: Record<string, string>;
}

export const DAILY_TASKS: DailyTask[] = [
  {
    id: 'wake',
    hour: 7,
    amountMl: 300,
    label: {
      tr: 'Sabah uyanır uyanmaz 1 büyük bardak',
      en: 'A big glass right after waking up',
      ar: 'كوب كبير فور الاستيقاظ',
      ru: 'Большой стакан сразу после пробуждения',
      de: 'Ein großes Glas direkt nach dem Aufwachen',
      fr: 'Un grand verre dès le réveil',
      es: 'Un vaso grande al despertar',
      it: 'Un bicchiere grande appena svegli',
      pt: 'Um copo grande ao acordar',
      nl: 'Een groot glas direct na het opstaan',
      pl: 'Duża szklanka tuż po obudzeniu',
      sv: 'Ett stort glas direkt efter uppvaknande',
      id: 'Segelas besar saat bangun tidur',
      vi: 'Một ly lớn ngay khi thức dậy',
      ja: '起床後すぐに大きなコップ1杯',
      ko: '기상 직후 큰 컵 1잔',
      zh: '起床后立刻喝一大杯',
      hi: 'सुबह उठते ही एक बड़ा गिलास',
    },
  },
  {
    id: 'pre_lunch',
    hour: 12,
    amountMl: 250,
    label: {
      tr: 'Öğle yemeğinden 30 dk önce 1 bardak',
      en: '1 glass 30 min before lunch',
      ar: 'كوب قبل الغداء بـ 30 دقيقة',
      ru: 'Стакан за 30 мин до обеда',
      de: 'Ein Glas 30 Min vor dem Mittagessen',
      fr: 'Un verre 30 min avant le déjeuner',
      es: 'Un vaso 30 min antes del almuerzo',
      it: 'Un bicchiere 30 min prima di pranzo',
      pt: 'Um copo 30 min antes do almoço',
      nl: 'Een glas 30 min voor de lunch',
      pl: 'Szklanka 30 min przed obiadem',
      sv: 'Ett glas 30 min före lunch',
      id: 'Segelas 30 menit sebelum makan siang',
      vi: 'Một ly 30 phút trước bữa trưa',
      ja: '昼食の30分前に1杯',
      ko: '점심 30분 전 1잔',
      zh: '午餐前30分钟喝一杯',
      hi: 'दोपहर के भोजन से 30 मिनट पहले 1 गिलास',
    },
  },
  {
    id: 'afternoon',
    hour: 15,
    amountMl: 300,
    label: {
      tr: 'Öğleden sonra enerji bardağı',
      en: 'Afternoon energy glass',
      ar: 'كوب طاقة بعد الظهر',
      ru: 'Дневной заряд энергии',
      de: 'Energie-Glas am Nachmittag',
      fr: 'Verre énergie de l\'après-midi',
      es: 'Vaso de energía por la tarde',
      it: 'Bicchiere energia pomeridiana',
      pt: 'Copo de energia à tarde',
      nl: 'Energieglas in de middag',
      pl: 'Energetyczna szklanka po południu',
      sv: 'Energiglas på eftermiddagen',
      id: 'Gelas energi sore hari',
      vi: 'Ly nước buổi chiều tiếp năng lượng',
      ja: '午後のエネルギー1杯',
      ko: '오후 활력 충전',
      zh: '下午能量补充',
      hi: 'दोपहर बाद ऊर्जा गिलास',
    },
  },
  {
    id: 'pre_workout',
    hour: 18,
    amountMl: 500,
    label: {
      tr: 'Spor / yürüyüş öncesi 500 ml',
      en: '500 ml before workout / walk',
      ar: '500 مل قبل التمرين',
      ru: '500 мл перед тренировкой',
      de: '500 ml vor Training / Spaziergang',
      fr: '500 ml avant sport / marche',
      es: '500 ml antes de ejercicio',
      it: '500 ml prima dello sport',
      pt: '500 ml antes do exercício',
      nl: '500 ml voor sport / wandeling',
      pl: '500 ml przed treningiem',
      sv: '500 ml före träning',
      id: '500 ml sebelum olahraga',
      vi: '500 ml trước khi tập / đi bộ',
      ja: '運動前に500ml',
      ko: '운동 전 500ml',
      zh: '运动前喝500ml',
      hi: 'व्यायाम से पहले 500 मि.ली.',
    },
  },
  {
    id: 'pre_sleep',
    hour: 21,
    amountMl: 200,
    label: {
      tr: 'Uykudan 2 saat önce son bardak',
      en: 'Last glass 2 h before sleep',
      ar: 'الكوب الأخير قبل النوم بساعتين',
      ru: 'Последний стакан за 2 ч до сна',
      de: 'Letztes Glas 2 h vor dem Schlafen',
      fr: 'Dernier verre 2 h avant le sommeil',
      es: 'Último vaso 2 h antes de dormir',
      it: 'Ultimo bicchiere 2 h prima di dormire',
      pt: 'Último copo 2 h antes de dormir',
      nl: 'Laatste glas 2 u voor het slapen',
      pl: 'Ostatnia szklanka 2 h przed snem',
      sv: 'Sista glaset 2 h före sömn',
      id: 'Gelas terakhir 2 jam sebelum tidur',
      vi: 'Ly cuối 2 giờ trước khi ngủ',
      ja: '就寝の2時間前に最後の1杯',
      ko: '취침 2시간 전 마지막 1잔',
      zh: '睡前2小时最后一杯',
      hi: 'सोने से 2 घंटे पहले आखिरी गिलास',
    },
  },
];

export function getTaskLabel(task: DailyTask, lang: LangCode): string {
  return (task.label as any)[lang] || task.label.en;
}
