import { LangCode } from './i18n';

// Motivational, non-medical quotes — 20 entries per language, 18 languages.
// All previous medical-claim quotes have been removed.
const QUOTES: Record<LangCode, string[]> = {
  en: [
    'Small sips, big changes. Every drop counts.',
    'Your body is your ocean — keep it flowing.',
    'Consistency beats perfection. Drink today.',
    'Water is the foundation of every good habit.',
    'One glass at a time. You\'ve got this.',
    'Hydration is self-care at its simplest.',
    'Progress, not perfection. Keep going.',
    'Every habit starts with a single sip.',
    'Your future self will thank you.',
    'Make hydration your superpower today.',
    'A hydrated mind thinks clearer.',
    'Today\'s water is tomorrow\'s energy.',
    'You are 60% water — honor that.',
    'Drink up, show up, never give up.',
    'The best time to drink water is now.',
    'Little by little, the ocean fills.',
    'Stay consistent, stay hydrated.',
    'Your goals start with a glass of water.',
    'Fuel your day the natural way.',
    'Sip by sip, day by day.',
  ],
  tr: [
    'Küçük yudumlar, büyük değişimler. Her damla sayılır.',
    'Vücudun senin okyanusun — akışında kalmasını sağla.',
    'Tutarlılık mükemmellikten önemlidir. Bugün iç.',
    'Su, her iyi alışkanlığın temelidir.',
    'Bir bardak, bir adım. Sen başarırsın.',
    'Hidrasyon, en sade haliyle öz bakımdır.',
    'Mükemmel değil, ilerleme önemli. Devam et.',
    'Her alışkanlık tek bir yudumla başlar.',
    'Gelecekteki sen sana teşekkür edecek.',
    'Hidrasyonu bugün süper gücün yap.',
    'İyi hidrate bir zihin daha net düşünür.',
    'Bugünün suyu yarının enerjisidir.',
    '%60’ın sudan — buna saygı göster.',
    'Su iç, ortaya çık, asla pes etme.',
    'Su içmenin en iyi zamanı şu an.',
    'Damla damla okyanus olur.',
    'Tutarlı kal, hidrate kal.',
    'Hedeflerin bir bardak suyla başlar.',
    'Gününe doğal yoldan yakıt ver.',
    'Yudum yudum, gün gün.',
  ],
  de: [
    'Kleine Schlucke, große Veränderungen. Jeder Tropfen zählt.',
    'Dein Körper ist dein Ozean — halte ihn im Fluss.',
    'Beständigkeit schlägt Perfektion. Trink heute.',
    'Wasser ist das Fundament jeder guten Gewohnheit.',
    'Ein Glas nach dem anderen. Du schaffst das.',
    'Hydration ist Selbstfürsorge in ihrer einfachsten Form.',
    'Fortschritt, nicht Perfektion. Mach weiter.',
    'Jede Gewohnheit beginnt mit einem einzigen Schluck.',
    'Dein zukünftiges Ich wird es dir danken.',
    'Mach Hydration heute zu deiner Superkraft.',
    'Ein hydrierter Geist denkt klarer.',
    'Das Wasser von heute ist die Energie von morgen.',
    'Du bestehst zu 60% aus Wasser — würdige das.',
    'Trink, sei da, gib nie auf.',
    'Die beste Zeit, Wasser zu trinken, ist jetzt.',
    'Tropfen für Tropfen wird der Ozean voll.',
    'Bleib beständig, bleib hydriert.',
    'Deine Ziele beginnen mit einem Glas Wasser.',
    'Treibe deinen Tag auf natürliche Weise an.',
    'Schluck für Schluck, Tag für Tag.',
  ],
  fr: [
    'Petites gorgées, grands changements. Chaque goutte compte.',
    'Ton corps est ton océan — garde-le en mouvement.',
    'La constance surpasse la perfection. Bois aujourd\'hui.',
    'L\'eau est la base de toute bonne habitude.',
    'Un verre à la fois. Tu peux le faire.',
    'L\'hydratation, c\'est prendre soin de soi simplement.',
    'Le progrès, pas la perfection. Continue.',
    'Chaque habitude commence par une seule gorgée.',
    'Ton futur toi te remerciera.',
    'Fais de l\'hydratation ton super-pouvoir aujourd\'hui.',
    'Un esprit hydraté pense plus clairement.',
    'L\'eau d\'aujourd\'hui est l\'énergie de demain.',
    'Tu es à 60% d\'eau — honore-la.',
    'Bois, montre-toi, n\'abandonne jamais.',
    'Le meilleur moment pour boire de l\'eau, c\'est maintenant.',
    'Petit à petit, l\'océan se remplit.',
    'Reste constant, reste hydraté.',
    'Tes objectifs commencent avec un verre d\'eau.',
    'Alimente ta journée de manière naturelle.',
    'Gorgée par gorgée, jour après jour.',
  ],
  es: [
    'Pequeños sorbos, grandes cambios. Cada gota cuenta.',
    'Tu cuerpo es tu océano — mantenlo fluyendo.',
    'La constancia supera a la perfección. Bebe hoy.',
    'El agua es la base de todo buen hábito.',
    'Un vaso a la vez. Tú puedes.',
    'La hidratación es autocuidado en su forma más simple.',
    'Progreso, no perfección. Sigue adelante.',
    'Cada hábito empieza con un solo sorbo.',
    'Tu yo futuro te lo agradecerá.',
    'Haz de la hidratación tu superpoder hoy.',
    'Una mente hidratada piensa con más claridad.',
    'El agua de hoy es la energía de mañana.',
    'Eres 60% agua — hónrala.',
    'Bebe, preséntate, nunca te rindas.',
    'El mejor momento para beber agua es ahora.',
    'Poco a poco, el océano se llena.',
    'Mantente constante, mantente hidratado.',
    'Tus metas empiezan con un vaso de agua.',
    'Alimenta tu día de forma natural.',
    'Sorbo a sorbo, día a día.',
  ],
  it: [
    'Piccoli sorsi, grandi cambiamenti. Ogni goccia conta.',
    'Il tuo corpo è il tuo oceano — mantienilo in movimento.',
    'La costanza batte la perfezione. Bevi oggi.',
    'L\'acqua è la base di ogni buona abitudine.',
    'Un bicchiere alla volta. Ce la fai.',
    'L\'idratazione è cura di sé nella sua forma più semplice.',
    'Progresso, non perfezione. Continua.',
    'Ogni abitudine inizia con un solo sorso.',
    'Il tuo io futuro ti ringrazierà.',
    'Rendi l\'idratazione il tuo superpotere oggi.',
    'Una mente idratata pensa più chiaramente.',
    'L\'acqua di oggi è l\'energia di domani.',
    'Sei 60% acqua — onorala.',
    'Bevi, presentati, non mollare mai.',
    'Il momento migliore per bere acqua è adesso.',
    'Goccia dopo goccia, l\'oceano si riempie.',
    'Resta costante, resta idratato.',
    'I tuoi obiettivi iniziano con un bicchiere d\'acqua.',
    'Alimenta la tua giornata in modo naturale.',
    'Sorso dopo sorso, giorno dopo giorno.',
  ],
  pt: [
    'Pequenos goles, grandes mudanças. Cada gota conta.',
    'Seu corpo é seu oceano — mantenha-o fluindo.',
    'A consistência supera a perfeição. Beba hoje.',
    'A água é a base de todo bom hábito.',
    'Um copo de cada vez. Você consegue.',
    'Hidratação é autocuidado em sua forma mais simples.',
    'Progresso, não perfeição. Continue.',
    'Todo hábito começa com um único gole.',
    'Seu eu futuro vai agradecer.',
    'Faça da hidratação seu superpoder hoje.',
    'Uma mente hidratada pensa com mais clareza.',
    'A água de hoje é a energia de amanhã.',
    'Você é 60% água — honre isso.',
    'Beba, apareça, nunca desista.',
    'O melhor momento para beber água é agora.',
    'Pouco a pouco, o oceano se enche.',
    'Mantenha-se constante, mantenha-se hidratado.',
    'Suas metas começam com um copo de água.',
    'Alimente seu dia de forma natural.',
    'Gole a gole, dia a dia.',
  ],
  ru: [
    'Маленькие глотки — большие перемены. Каждая капля важна.',
    'Твоё тело — твой океан, держи его в движении.',
    'Постоянство важнее совершенства. Пей сегодня.',
    'Вода — основа любой хорошей привычки.',
    'По одному стакану за раз. У тебя получится.',
    'Гидратация — забота о себе в самом простом виде.',
    'Прогресс, а не совершенство. Продолжай.',
    'Каждая привычка начинается с одного глотка.',
    'Будущий ты скажет спасибо.',
    'Сделай гидратацию своей суперспособностью сегодня.',
    'Хорошо увлажнённый ум мыслит яснее.',
    'Вода сегодня — энергия завтра.',
    'Ты на 60% состоишь из воды — почти это.',
    'Пей, будь рядом, никогда не сдавайся.',
    'Лучшее время выпить воды — сейчас.',
    'Капля за каплей наполняется океан.',
    'Будь постоянным — будь увлажнённым.',
    'Твои цели начинаются со стакана воды.',
    'Заряжай свой день естественным способом.',
    'Глоток за глотком, день за днём.',
  ],
  ja: [
    '小さなひと口、大きな変化。一滴一滴が大切です。',
    'あなたの体は海。流れを止めないで。',
    '完璧より継続。今日も水を飲もう。',
    '水はすべての良い習慣の土台です。',
    '一杯ずつ、あなたならできる。',
    '水分補給はもっともシンプルなセルフケア。',
    '完璧ではなく進歩を。歩み続けよう。',
    'すべての習慣は一口の水から始まる。',
    '未来のあなたが感謝します。',
    '今日、水分補給をあなたの超能力にしよう。',
    '水分が満ちた心はよりクリアに考える。',
    '今日の水は明日のエネルギー。',
    'あなたの60%は水 — それを大切に。',
    '飲んで、姿を見せて、決して諦めない。',
    '水を飲む最高のタイミングは今。',
    '少しずつ、海は満ちていく。',
    '続けて、潤いをキープ。',
    'あなたの目標は一杯の水から始まる。',
    '自然な方法で一日に活力を。',
    '一口ずつ、一日ずつ。',
  ],
  ko: [
    '작은 한 모금이 큰 변화를 만듭니다. 한 방울도 소중해요.',
    '당신의 몸은 바다입니다. 흐름을 유지하세요.',
    '꾸준함이 완벽함을 이깁니다. 오늘 마셔요.',
    '물은 모든 좋은 습관의 기초입니다.',
    '한 잔씩, 당신은 할 수 있어요.',
    '수분 보충은 가장 단순한 자기 돌봄입니다.',
    '완벽이 아닌 진보를. 계속 나아가요.',
    '모든 습관은 한 모금에서 시작됩니다.',
    '미래의 당신이 고마워할 거예요.',
    '오늘 수분 보충을 당신의 초능력으로 만들어요.',
    '수분이 충분한 마음은 더 또렷하게 생각합니다.',
    '오늘의 물은 내일의 에너지.',
    '당신은 60%가 물 — 그것을 존중하세요.',
    '마시고, 나타나고, 절대 포기하지 마세요.',
    '물 마실 가장 좋은 때는 바로 지금.',
    '조금씩, 바다가 채워집니다.',
    '꾸준히, 수분을 유지하세요.',
    '당신의 목표는 물 한 잔에서 시작됩니다.',
    '자연스러운 방법으로 하루를 채우세요.',
    '한 모금씩, 하루하루.',
  ],
  zh: [
    '小口小口，大改变。每一滴都重要。',
    '你的身体是你的海洋——让它流动起来。',
    '坚持胜过完美。今天就喝吧。',
    '水是每个好习惯的基石。',
    '一次一杯，你做得到。',
    '补水是最简单的自我关怀。',
    '进步胜于完美，继续前行。',
    '每个习惯都从一小口开始。',
    '未来的你会感谢你。',
    '今天就让补水成为你的超能力。',
    '充分补水的大脑更清晰。',
    '今天的水就是明天的能量。',
    '你的身体60%是水——尊重它。',
    '喝水，出现，永不放弃。',
    '喝水的最佳时机就是现在。',
    '一点一滴，汇成海洋。',
    '保持持续，保持水润。',
    '你的目标从一杯水开始。',
    '用自然的方式为一天充电。',
    '一口一口，一天一天。',
  ],
  ar: [
    'رشفات صغيرة، تغييرات كبيرة. كل قطرة مهمة.',
    'جسدك هو محيطك — أبقِه يتدفق.',
    'الاستمرارية تتفوق على الكمال. اشرب اليوم.',
    'الماء أساس كل عادة جيدة.',
    'كوب واحد في كل مرة. أنت قادر على ذلك.',
    'الترطيب هو أبسط أشكال العناية بالنفس.',
    'التقدم وليس الكمال. واصل المسير.',
    'كل عادة تبدأ برشفة واحدة.',
    'نفسك المستقبلية ستشكرك.',
    'اجعل الترطيب قوتك الخارقة اليوم.',
    'العقل المرطّب يفكّر بوضوح أكبر.',
    'ماء اليوم هو طاقة الغد.',
    '60٪ منك ماء — احترِم ذلك.',
    'اشرب، احضر، لا تستسلم أبداً.',
    'أفضل وقت لشرب الماء هو الآن.',
    'قليلاً قليلاً، يمتلئ المحيط.',
    'كن ثابتاً، ابقَ مرطّباً.',
    'أهدافك تبدأ بكوب من الماء.',
    'زوّد يومك بالطاقة بالطريقة الطبيعية.',
    'رشفة برشفة، يوماً بيوم.',
  ],
  nl: [
    'Kleine slokjes, grote veranderingen. Elke druppel telt.',
    'Je lichaam is je oceaan — houd het stromend.',
    'Consistentie wint van perfectie. Drink vandaag.',
    'Water is de basis van elke goede gewoonte.',
    'Eén glas tegelijk. Jij kunt dit.',
    'Hydratatie is zelfzorg in zijn eenvoudigste vorm.',
    'Voortgang, niet perfectie. Ga door.',
    'Elke gewoonte begint met één slokje.',
    'Je toekomstige zelf zal je dankbaar zijn.',
    'Maak hydratatie vandaag jouw superkracht.',
    'Een gehydrateerde geest denkt helderder.',
    'Het water van vandaag is de energie van morgen.',
    'Je bent voor 60% water — eer dat.',
    'Drink, verschijn, geef nooit op.',
    'Het beste moment om water te drinken is nu.',
    'Beetje bij beetje vult de oceaan zich.',
    'Blijf consistent, blijf gehydrateerd.',
    'Je doelen beginnen met een glas water.',
    'Geef je dag energie op natuurlijke wijze.',
    'Slokje voor slokje, dag voor dag.',
  ],
  pl: [
    'Małe łyki, wielkie zmiany. Każda kropla się liczy.',
    'Twoje ciało to twój ocean — niech płynie.',
    'Konsekwencja pokonuje doskonałość. Wypij dziś.',
    'Woda to fundament każdego dobrego nawyku.',
    'Jedna szklanka na raz. Dasz radę.',
    'Nawadnianie to najprostsza forma dbania o siebie.',
    'Postęp, nie doskonałość. Idź dalej.',
    'Każdy nawyk zaczyna się od jednego łyku.',
    'Twoje przyszłe ja ci podziękuje.',
    'Uczyń nawadnianie swoją supermocą dzisiaj.',
    'Nawodniony umysł myśli jaśniej.',
    'Dzisiejsza woda to jutrzejsza energia.',
    'W 60% jesteś z wody — szanuj to.',
    'Pij, bądź obecny, nigdy się nie poddawaj.',
    'Najlepszy czas na wodę to teraz.',
    'Po trochu wypełnia się ocean.',
    'Bądź konsekwentny, bądź nawodniony.',
    'Twoje cele zaczynają się od szklanki wody.',
    'Naturalnie dodaj sobie energii na cały dzień.',
    'Łyk za łykiem, dzień za dniem.',
  ],
  sv: [
    'Små klunkar, stora förändringar. Varje droppe räknas.',
    'Din kropp är ditt hav — håll det i rörelse.',
    'Konsekvens slår perfektion. Drick idag.',
    'Vatten är grunden för varje god vana.',
    'Ett glas i taget. Du klarar det.',
    'Hydrering är egenvård i sin enklaste form.',
    'Framsteg, inte perfektion. Fortsätt.',
    'Varje vana börjar med en enda klunk.',
    'Ditt framtida jag kommer att tacka dig.',
    'Gör hydrering till din superkraft idag.',
    'Ett hydrerat sinne tänker klarare.',
    'Dagens vatten är morgondagens energi.',
    'Du består till 60% av vatten — hedra det.',
    'Drick, dyk upp, ge aldrig upp.',
    'Bästa tiden att dricka vatten är nu.',
    'Lite i taget fylls havet.',
    'Var konsekvent, håll dig hydrerad.',
    'Dina mål börjar med ett glas vatten.',
    'Ge din dag energi på det naturliga sättet.',
    'Klunk för klunk, dag för dag.',
  ],
  hi: [
    'छोटे घूंट, बड़े बदलाव। हर बूंद मायने रखती है।',
    'तुम्हारा शरीर तुम्हारा समुद्र है — इसे बहता हुआ रखो।',
    'निरंतरता पूर्णता से बेहतर है। आज पियो।',
    'पानी हर अच्छी आदत की नींव है।',
    'एक गिलास एक बार में। तुम कर सकते हो।',
    'हाइड्रेशन सबसे सरल आत्म-देखभाल है।',
    'पूर्णता नहीं, प्रगति। चलते रहो।',
    'हर आदत एक घूंट से शुरू होती है।',
    'भविष्य का तुम तुम्हें धन्यवाद देगा।',
    'आज हाइड्रेशन को अपनी सुपरपावर बनाओ।',
    'हाइड्रेटेड मन अधिक स्पष्ट सोचता है।',
    'आज का पानी कल की ऊर्जा है।',
    'तुम 60% पानी हो — इसका सम्मान करो।',
    'पियो, दिखो, कभी हार मत मानो।',
    'पानी पीने का सबसे अच्छा समय अभी है।',
    'धीरे-धीरे, समुद्र भर जाता है।',
    'निरंतर रहो, हाइड्रेटेड रहो।',
    'तुम्हारे लक्ष्य एक गिलास पानी से शुरू होते हैं।',
    'अपने दिन को प्राकृतिक तरीके से ऊर्जा दो।',
    'घूंट दर घूंट, दिन दर दिन।',
  ],
  id: [
    'Tegukan kecil, perubahan besar. Setiap tetes berarti.',
    'Tubuhmu adalah lautanmu — jaga agar tetap mengalir.',
    'Konsistensi mengalahkan kesempurnaan. Minumlah hari ini.',
    'Air adalah fondasi setiap kebiasaan baik.',
    'Satu gelas pada satu waktu. Kamu bisa.',
    'Hidrasi adalah perawatan diri yang paling sederhana.',
    'Kemajuan, bukan kesempurnaan. Terus maju.',
    'Setiap kebiasaan dimulai dari satu tegukan.',
    'Dirimu di masa depan akan berterima kasih.',
    'Jadikan hidrasi kekuatan supermu hari ini.',
    'Pikiran yang terhidrasi berpikir lebih jernih.',
    'Air hari ini adalah energi esok hari.',
    'Tubuhmu 60% air — hormatilah itu.',
    'Minumlah, hadirlah, jangan pernah menyerah.',
    'Waktu terbaik minum air adalah sekarang.',
    'Sedikit demi sedikit, samudra terisi penuh.',
    'Tetaplah konsisten, tetaplah terhidrasi.',
    'Tujuanmu dimulai dari segelas air.',
    'Isi harimu dengan cara alami.',
    'Tegukan demi tegukan, hari demi hari.',
  ],
  vi: [
    'Từng ngụm nhỏ, thay đổi lớn. Mỗi giọt đều quan trọng.',
    'Cơ thể bạn là đại dương của bạn — hãy để nó luôn chảy.',
    'Kiên trì hơn cả hoàn hảo. Hãy uống hôm nay.',
    'Nước là nền tảng của mọi thói quen tốt.',
    'Mỗi lần một ly. Bạn làm được.',
    'Cấp nước là cách chăm sóc bản thân đơn giản nhất.',
    'Tiến bộ, không phải hoàn hảo. Tiếp tục đi.',
    'Mọi thói quen đều bắt đầu từ một ngụm.',
    'Bạn của tương lai sẽ cảm ơn bạn.',
    'Hôm nay hãy biến cấp nước thành siêu năng lực của bạn.',
    'Một tâm trí được cấp đủ nước nghĩ rõ ràng hơn.',
    'Nước hôm nay là năng lượng ngày mai.',
    'Bạn là 60% nước — hãy trân trọng điều đó.',
    'Hãy uống, có mặt, đừng bao giờ bỏ cuộc.',
    'Thời điểm tốt nhất để uống nước là ngay bây giờ.',
    'Từng chút một, đại dương được lấp đầy.',
    'Hãy kiên trì, hãy đủ nước.',
    'Mục tiêu của bạn bắt đầu bằng một ly nước.',
    'Tiếp năng lượng cho ngày của bạn theo cách tự nhiên.',
    'Từng ngụm, từng ngày.',
  ],
};

/**
 * Returns a deterministic, daily-rotating quote that differs each day.
 * The quote is the same throughout a given calendar day, then changes the next day.
 * Random-feeling order is achieved with a multiplicative hash over day-of-year + year.
 */
export function getQuoteForDay(lang: LangCode, date: Date = new Date()): string {
  const list = QUOTES[lang] || QUOTES.en;
  const start = new Date(date.getFullYear(), 0, 0).getTime();
  const dayOfYear = Math.floor((date.getTime() - start) / 86400000);
  const seed = (dayOfYear * 2654435761 + date.getFullYear() * 9176) >>> 0;
  const idx = seed % list.length;
  return list[idx];
}

/** Truly random quote (used for ad-hoc notification bodies). */
export function getRandomQuote(lang: LangCode): string {
  const list = QUOTES[lang] || QUOTES.en;
  return list[Math.floor(Math.random() * list.length)];
}
